name: Boost.Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: maswag/monaa-test-env
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: default build
      run: |
        mkdir -p build
        cd build && cmake .. && make

  gcc_unit_test:
    runs-on: ubuntu-latest
    container: maswag/monaa-test-env
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: set gcc env
      run: |
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
    - name: build and test
      run: |
        mkdir -p gcc_build
        cd gcc_build && cmake .. && make unit_test && make test

  clang_unit_test:
    runs-on: ubuntu-latest
    container: maswag/monaa-test-env
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: set clang env
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
    - name: build and test
      run: |
        mkdir -p clang_build
        cd clang_build && cmake .. && make unit_test && make test

  ubuntu_focal:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install cmake libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && make test

  ubuntu_jammy:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install build-essential cmake libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && make test

  macOS_BigSur:
    runs-on: macos-11
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: brew install eigen boost
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test

  macOS_Monterey:
    runs-on: macos-12
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: brew install eigen boost
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test

  arch_linux:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: pacman -Syu cmake eigen boost tbb doxygen --noconfirm
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test
